[package]
name = "baby-crawler-network"
version = "0.1.0"
edition = "2024"

[package.metadata.turbo]
user = "185d03bd-a195-4a88-a267-2d433c78c598"

[dependencies]
turbo = { version = "4.0.0-alpha.36", package = "turbo-genesis-sdk" }
borsh = "1.3"
serde = { version = "1.0", features = ["derive"] }
bitflags = "1.3"

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
