[package]
name = "baby-crawler-network"
version = "0.1.0"
edition = "2024"

[package.metadata.turbo]
user = "ac82704e-e1f6-4e64-a102-63f817d1df73"

[dependencies]
turbo = { version = "4.0.0-alpha.0", package = "turbo-genesis-sdk" }
borsh = "1.3"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
