name = "baby-crawler-network"
version = "0.1.0"
description = "An awesome game made in Turbo!"
authors = ["Anonymous"]

[canvas]
width = 256
height = 144

[turbo-os]
api-url = "https://os.turbo.computer"