name = "baby-crawler-network"
version = "1.0.0"
description = "Help your baby escape from the dungeon!"
authors = ["1min", "Pegasus Games"]

[canvas]
width = 360
height = 640

[turbo-os]
api-url = "https://os.turbo.computer"